# this is an old test, locally it is working, but not on github
name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./StoryQuest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.0'
        cache: 'npm'
        cache-dependency-path: './StoryQuest/package-lock.json'

    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test -- --watchAll=false

    - name: Report test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./StoryQuest/coverage